version: '3.7'
services:
  swa_eureka:
    image: 'swa/eureka'
    container_name: swa_eureka
    env_file:
      - ./.env
    restart: always
    volumes:
      - /opt/workspace/nerdcode/docker/data/logs:/logs:rw
    ports:
      - "${PORT_OUT}:8761"
    mem_limit: 512m
    mem_reservation: 256m
#    networks:
#      microservice_network:
#        aliases:
#          - eureka-server
#  swa_zuul:
#    image: 'swa/zuul'
#    container_name: swa_zuul
#    restart: always
#    volumes:
#      - /opt/workspace/nerdcode/docker/data/logs:/logs:rw
#    ports:
#      - "8081:8081"
#    mem_limit: 256m
#    mem_reservation: 128m
#    depends_on:
#      - "swa/eureka"
#    networks:
#      microservice_network:
#
#networks:
#  microservice_network:
#    ipam:
#      driver: default