name: "{{SERVICE}}"

on:
  push:
    paths:
      - "microservices/{{SERVICE}}/**"
      - ".github/workflows/{{SERVICE}}.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd microservices/{{SERVICE}}
          run_tests.sh
