openapi: 3.0.1
info:
  title: High Score service
  description: Microservice API for High scores
  version: 1.0-oas3
servers:
  - url: 'http://localhost:8003/api/v1'
paths:
  /high_score:
    get:
      tags:
        - high_score
      summary: Get the top 10 users
      operationId: get_high_score_top
      responses:
        '200':
          description: Top 10 users returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HighScoreArray'
  '/high_score/{username}':
    get:
      tags:
        - high_score
      summary: Get the ranking of the desired user
      operationId: get_user_high_score
      parameters:
        - name: username
          in: path
          description: The username that needs to be fetched
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Top 10 users returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HighScore'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'common_components.yaml#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: 'common_components.yaml#/components/schemas/Error'
        '422':
          description: Invalid username supplied
          content:
            application/json:
              schema:
                $ref: 'common_components.yaml#/components/schemas/Error'
components:
  schemas:
    HighScore:
      description: high score object
      type: object
      properties:
        username:
          type: string
        wins:
          type: integer
        loses:
          type: integer
        ragequits:
          type: integer
        winrate:
          type: number
          readOnly: true
        rank:
          type: integer
          readOnly: true     
    HighScoreArray:
      description: array of high scores
      type: object
      properties:
        high_scores:
          type: array
          items:
            $ref: '#/components/schemas/HighScore'
    FinishedGame:
      description: finished game to process from RabbitMQ - is here only for model codegen
      $ref: 'common_components.yaml#/components/schemas/FinishedGameHighScore'
