openapi: 3.0.1
info:
  title: Replayz
  description: Stores and serves replays of the game `connect 5`.
  contact:
    email: neuvimat@fel.cvut.cz
  version: 1.0.0
servers:
- url: http://localhost/api/v3
tags:
- name: replay
  description: Sum stuff 'bout 'em replayz
paths:
  /replay:
    put:
      tags:
      - replay
      summary: Update an existing replay
      operationId: update_replay
      requestBody:
        description: Updates a replay based on the supplied ID. All fields in the
          schema are required.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Replay'
        required: true
      responses:
        "200":
          description: All is fine
          content: {}
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Replay not found
          content: {}
      x-swagger-router-controller: Replay
    post:
      tags:
      - replay
      summary: Add a new replay to the store
      operationId: add_replay
      requestBody:
        description: Replay object to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Replay'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Replay'
        "405":
          description: Invalid input
          content: {}
      x-swagger-router-controller: Replay
  /replay/filter:
    post:
      tags:
      - replay
      summary: Search across all the replays
      description: "Filters through replays based on supplied filters. Returns abridged\
        \ version of replays, where the specific turns (field `plays`) are not listed\
        \ for brevity. If you need that, ask for a specific replay by its id. Also\
        \ it is okay to use post method for liters because mongoDB does it too :)"
      operationId: filter_replays
      requestBody:
        description: Filter criterions
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReplayFilter'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReplayArray'
        "400":
          description: Invalid request
          content: {}
      x-swagger-router-controller: Replay
  /replay/{replayId}:
    get:
      tags:
      - replay
      summary: Get a replay by ID
      description: Returns a single replay by its ID
      operationId: get_replay_by_id
      parameters:
      - name: replayId
        in: path
        description: ID of replay to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Replay'
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Replay not found
          content: {}
      x-swagger-router-controller: Replay
    delete:
      tags:
      - replay
      summary: Deletes a replay
      operationId: delete_replay
      parameters:
      - name: replayId
        in: path
        description: Replay id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: success
          content: {}
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Replay not found
          content: {}
      x-swagger-router-controller: Replay
components:
  schemas:
    Replay:
      type: object
      properties:
        id:
          type: integer
          format: int64
        player1Id:
          type: integer
          description: The host of the match
          format: int64
        player2Id:
          type: integer
          description: The other player (i.e. not the host)
          format: int64
        winner:
          type: integer
          description: ID of the winner
          format: int64
        rounds:
          type: integer
          description: How many rounds the match took
          format: int64
        date:
          type: string
          format: date-time
        completed:
          type: boolean
          description: Whether the game finished as expected (`true`) or the opponent
            has left the game (`false`)
        plays:
          maxItems: 2
          minItems: 2
          type: array
          items:
            type: integer
      example:
        date: 2000-01-23T04:56:07.000+00:00
        player1Id: 6
        winner: 5
        plays:
        - 2
        - 2
        player2Id: 1
        id: 0
        completed: true
        rounds: 5
    ReplayShort:
      type: object
      properties:
        id:
          type: integer
          format: int64
        player1Id:
          type: integer
          description: The host of the match
          format: int64
        player2Id:
          type: integer
          description: The other player (i.e. not the host)
          format: int64
        rounds:
          type: integer
          description: How many rounds the match took
          format: int64
        date:
          type: string
          format: date-time
        completed:
          type: boolean
          description: Whether the game finished as expected (`true`) or the opponent
            has left the game (`false`)
      example:
        date: 2000-01-23T04:56:07.000+00:00
        player1Id: 6
        player2Id: 1
        id: 0
        completed: true
        rounds: 5
    ReplayArray:
      type: array
      items:
        $ref: '#/components/schemas/ReplayShort'
    ReplayFilter:
      type: object
      properties:
        player1Id:
          type: integer
          description: The host of the match
          format: int64
        player2Id:
          type: integer
          description: The other player (i.e. not the host)
          format: int64
        date:
          $ref: '#/components/schemas/ReplayFilter_date'
        completed:
          type: boolean
          description: Whether the game finished as expected (`true`) or the opponent
            has left the game (`false`)
        plays:
          maxItems: 2
          minItems: 2
          type: array
          items:
            type: integer
        rounds:
          $ref: '#/components/schemas/ReplayFilter_rounds'
    ReplayFilter_date:
      type: object
      properties:
        before:
          type: string
          format: date-time
        after:
          type: string
          format: date-time
    ReplayFilter_rounds:
      type: object
      properties:
        gte:
          type: integer
          description: Greater than or equal to this value
          format: int64
        lte:
          type: integer
          description: Less than or equal to this value
          format: int64
