version: "3.7"

services:
  user_db:
    image: mysql
    container_name: user_db_container
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./database/scheme.sql:/docker-entrypoint-initdb.d/scheme.sql:rw
      - db_data:/var/lib/mysql

  #### FOR DEBUGGING PUPROSES ####
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    depends_on:
      - user_db
    environment:
      PMA_HOST: user_db
    links:
      - user_db:user_db
    ports:
      - 8080:80
  ################################

volumes:
  db_data: