version: "3.7"

services:
  user_db:
    image: mysql
    container_name: user_db_container
    env_file: .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  app:
    container_name: user_svc_container
    depends_on:
      - user_db
    env_file: .env
    ports:
      - ${APP_PORT_OUT}:${APP_PORT}
    build: .
    command: python3 -m user_svc

  #### FOR DEBUGGING PURPOSES ####
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    depends_on:
      - user_db
    environment:
      PMA_HOST: user_db
    links:
      - user_db:user_db
    ports:
      - 8080:80
  ################################

volumes:
  db_data: