version: "3.7"

services:
  user_db:
    image: mysql
    container_name: swa_user_db
    env_file: .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    cap_add:
      - SYS_NICE

  app:
    container_name: swa_user_svc
    depends_on:
      - user_db
    env_file: .env
    ports:
      - ${APP_PORT_OUT}:${APP_PORT}
    build: .
    command: python3 -u -m user_svc

  #### FOR DEBUGGING PURPOSES ####
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: swa_user_phpadmin
    depends_on:
      - user_db
    environment:
      PMA_HOST: user_db
    links:
      - user_db:user_db
    ports:
      - 8081:80
  ################################

volumes:
  db_data: