version: "3.7"

services:
  high_score_db:
    image: mysql
    container_name: swa_high_score_db
    env_file: .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    cap_add:
      - SYS_NICE

  app:
    container_name: swa_high_score_svc
    depends_on:
      - high_score_db
    env_file: .env
    ports:
      - ${APP_PORT_OUT}:${APP_PORT}
    build: .
    command: python3 -u -m high_score_svc

  #### FOR DEBUGGING PURPOSES ####
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: high_score_phpadmin
    depends_on:
      - high_score_db
    environment:
      PMA_HOST: high_score_db
    links:
      - high_score_db:high_score_db
    ports:
      - 8083:80
  ################################

volumes:
  db_data: