version: '3'
services:
  swa_ui:
    build: .
    image: swa/ui/service
    # Pro škálování je nutné nemít konkrétní jméno servicy
    # container_name: nodejs
    env_file: .env
    ports:
      - ${ENDPOINT_PORT}:80