openapi: 3.0.1
info:
  title: Users
  description: Microservice API for user management
  version: 1.0-oas3
servers:
- url: http://localhost:8001/api/v1
paths:
  /user:
    post:
      tags:
      - user
      summary: Create a new user
      operationId: create_user
      requestBody:
        description: User to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: User was created and is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "409":
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Invalid user supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: user_svc.controllers.user_controller
  /user/{username}:
    get:
      tags:
      - user
      summary: Get user by username
      operationId: get_user_by_username
      parameters:
      - name: username
        in: path
        description: The username that needs to be fetched
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Invalid username supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: user_svc.controllers.user_controller
    put:
      tags:
      - user
      summary: Update user
      operationId: update_user
      parameters:
      - name: username
        in: path
        description: user that needs to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: The last IP to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        "200":
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Invalid data supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: user_svc.controllers.user_controller
    delete:
      tags:
      - user
      summary: Delete user
      operationId: delete_user
      parameters:
      - name: username
        in: path
        description: The user that needs to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: User deleted successfully
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Invalid username supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: user_svc.controllers.user_controller
  /userdetail/{username}:
    get:
      tags:
      - user
      summary: User with other aggregated data
      operationId: get_userdetail
      parameters:
      - name: username
        in: path
        description: The username that needs to be fetched
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetail'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Invalid username supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: user_svc.controllers.user_controller
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        origin_ip:
          type: string
        last_ip:
          type: string
        created:
          type: integer
          readOnly: true
        updated:
          type: integer
          readOnly: true
      description: user object
      example:
        last_ip: last_ip
        created: 0
        updated: 6
        origin_ip: origin_ip
        username: username
    UserDetail:
      properties:
        achievements:
          type: array
          items:
            $ref: '#/components/schemas/Achievement'
        high_score:
          $ref: '#/components/schemas/HighScore'
      description: user object with aggregated data
      example:
        achievements:
        - name: name
          description: description
          achievement_points: 0
        - name: name
          description: description
          achievement_points: 0
        high_score:
          wins: 6
          ragequits: 5
          loses: 1
          rank: 5
          username: username
      allOf:
      - $ref: '#/components/schemas/User'
      - type: object
    Error:
      type: object
      properties:
        detail:
          type: string
        status:
          type: integer
        title:
          type: string
        type:
          type: string
      description: Error response
    Achievement:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        achievement_points:
          type: integer
      description: achievement object
      example:
        name: name
        description: description
        achievement_points: 0
    HighScore:
      type: object
      properties:
        username:
          type: string
        wins:
          type: integer
        loses:
          type: integer
        ragequits:
          type: integer
        rank:
          type: integer
      description: high score object
      example:
        wins: 6
        ragequits: 5
        loses: 1
        rank: 5
        username: username
    body:
      required:
      - ip
      type: object
      properties:
        ip:
          type: string

