name: "achievement_svc"

on:
  push:
    paths:
      - "microservices/achievement_svc/**"
      - ".github/workflows/achievement_svc.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd microservices/achievement_svc
          run_tests.sh
