name: "game_svc"

on:
  push:
    paths:
      - "microservices/game_svc/**"
      - ".github/workflows/game_svc.yaml"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd microservices/game_svc
          ./run_tests.sh
