name: "high_score_svc"

on:
  push:
    paths:
      - "microservices/high_score_svc/**"
      - ".github/workflows/high_score_svc.yaml"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd microservices/high_score_svc
          ./run_tests.sh
