name: "lobby_svc"

on:
  push:
    paths:
      - "microservices/lobby_svc/**"
      - ".github/workflows/lobby_svc.yaml"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd microservices/lobby_svc
          ./run_tests.sh
