name: "{{ROUTE}}"

on:
  push:
    paths:
      - "microservices/{{ROUTE}}/**"
      - ".github/workflows/{{ROUTE}}.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd microservices/{{ROUTE}}
          run_tests.sh
